# Generated by Django 5.1.1 on 2024-10-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/laboratorios/'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='materiales',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='objetivo',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='procedimiento',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='resultados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='descripcion',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
